version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: cdb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: oretania
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wporetania
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wpred   
  
  wordpress:
    build: ./   
    image: imgwordpresspdo   
    container_name: cwp
    depends_on:
      - db
    restart: always
    ports:
      - "8090:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wporetania
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./:/var/www/html
      #Redes a usar
    networks:
      - wpred 
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cphpmyadmin
    depends_on:
      - db
    restart: always
    ports: 
      - 8095:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: oretania
    networks:
      - wpred
networks:
  wpred:
    driver: bridge

volumes:
  db_data: